-- Monk Play MySQL Workbench Database File
-- Open this file in MySQL Workbench and click the lightning/run button.
-- It creates the database, tables, indexes, safe views, and useful checking queries.
-- To see real-time changes in MySQL Workbench, rerun the SELECT queries at the bottom
-- or right-click the result grid and choose Refresh.

CREATE DATABASE IF NOT EXISTS flask_crud
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE flask_crud;

-- =========================================================
-- USERS
-- Passwords are stored as one-way hashes generated by Flask.
-- Do not store plain-text passwords in this table.
-- Example hash format from the app:
-- pbkdf2:sha256:1000000$salt$hashvalue
-- =========================================================
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    google_id VARCHAR(255) UNIQUE NULL,
    avatar_url VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_users_role (role),
    INDEX idx_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Upgrade older Monk Play databases without breaking existing records.
DROP PROCEDURE IF EXISTS add_column_if_missing;
DELIMITER //
CREATE PROCEDURE add_column_if_missing(
    IN table_name_value VARCHAR(64),
    IN column_name_value VARCHAR(64),
    IN column_definition_value TEXT
)
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = DATABASE()
            AND table_name = table_name_value
            AND column_name = column_name_value
    ) THEN
        SET @alter_sql = CONCAT(
            'ALTER TABLE `',
            table_name_value,
            '` ADD COLUMN `',
            column_name_value,
            '` ',
            column_definition_value
        );
        PREPARE statement_to_run FROM @alter_sql;
        EXECUTE statement_to_run;
        DEALLOCATE PREPARE statement_to_run;
    END IF;
END//
DELIMITER ;

CALL add_column_if_missing('users', 'created_at', 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP');
CALL add_column_if_missing('users', 'updated_at', 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
CALL add_column_if_missing('users', 'google_id', 'VARCHAR(255) UNIQUE NULL');
CALL add_column_if_missing('users', 'avatar_url', 'VARCHAR(255) NULL');
DROP PROCEDURE IF EXISTS add_column_if_missing;

-- =========================================================
-- LOGIN EVENTS
-- Stores every login attempt for checking in MySQL Workbench.
-- The submitted password is never stored here. Passwords stay hashed
-- only in users.password.
-- =========================================================
CREATE TABLE IF NOT EXISTS login_events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NULL,
    email VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(255) NULL,
    password_storage_status VARCHAR(80) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_login_events_user_id (user_id),
    INDEX idx_login_events_email (email),
    INDEX idx_login_events_status (status),
    INDEX idx_login_events_created_at (created_at),
    CONSTRAINT fk_login_events_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- IMPORTED PLAYLISTS
-- Stores Spotify playlists and the app's internal Manual Music playlist.
-- =========================================================
CREATE TABLE IF NOT EXISTS imported_playlists (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    spotify_playlist_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    owner_name VARCHAR(255) NULL,
    image_url VARCHAR(500) NULL,
    spotify_url VARCHAR(500) NULL,
    track_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_user_playlist (user_id, spotify_playlist_id),
    INDEX idx_imported_playlists_user_id (user_id),
    INDEX idx_imported_playlists_name (name),
    CONSTRAINT fk_imported_playlists_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- IMPORTED PLAYLIST TRACKS
-- Stores songs from Spotify imports and manual admin uploads.
-- =========================================================
CREATE TABLE IF NOT EXISTS imported_playlist_tracks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    imported_playlist_id INT NOT NULL,
    spotify_track_id VARCHAR(255) NULL,
    track_name VARCHAR(255) NOT NULL,
    artist_names VARCHAR(255) NULL,
    album_name VARCHAR(255) NULL,
    track_description TEXT NULL,
    spotify_url VARCHAR(500) NULL,
    local_file_url VARCHAR(500) NULL,
    source_type VARCHAR(30) NOT NULL DEFAULT 'spotify',
    duration_ms INT NOT NULL DEFAULT 0,
    track_position INT NOT NULL,
    INDEX idx_tracks_playlist_id (imported_playlist_id),
    INDEX idx_tracks_source_type (source_type),
    INDEX idx_tracks_name (track_name),
    CONSTRAINT fk_imported_playlist_tracks_playlist
        FOREIGN KEY (imported_playlist_id) REFERENCES imported_playlists(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- SAFE USER VIEW
-- Use this view when you want users/admins to see account data.
-- It does NOT expose the password hash.
-- =========================================================
CREATE OR REPLACE VIEW safe_user_profiles AS
SELECT
    id,
    name,
    email,
    role,
    created_at,
    updated_at,
    CASE
        WHEN password LIKE 'pbkdf2:%'
            OR password LIKE 'scrypt:%'
            OR password LIKE 'argon2:%'
        THEN 'Encrypted password hash stored'
        ELSE 'Password needs reset to replace old unsafe value'
    END AS password_storage_status
FROM users;

-- Login event details for MySQL Workbench.
-- This joins login attempts to user records without exposing passwords.
CREATE OR REPLACE VIEW login_event_details AS
SELECT
    login_events.id,
    login_events.user_id,
    COALESCE(users.name, 'Unknown user') AS user_name,
    login_events.email,
    COALESCE(users.role, 'guest') AS user_role,
    login_events.status,
    login_events.password_storage_status,
    login_events.ip_address,
    login_events.user_agent,
    login_events.created_at
FROM login_events
LEFT JOIN users
    ON users.id = login_events.user_id;

-- Live-safe user records for MySQL Workbench.
-- This view is meant for checking current users without exposing passwords.
CREATE OR REPLACE VIEW live_user_records AS
SELECT
    id,
    name,
    email,
    role,
    created_at,
    updated_at,
    NOW() AS checked_at
FROM users;

-- =========================================================
-- LIBRARY SUMMARY VIEW
-- Safe summary of playlist and track records per user.
-- =========================================================
CREATE OR REPLACE VIEW user_library_summary AS
SELECT
    users.id AS user_id,
    users.name,
    users.email,
    users.role,
    COUNT(DISTINCT imported_playlists.id) AS playlist_count,
    COUNT(imported_playlist_tracks.id) AS track_count,
    SUM(CASE WHEN imported_playlist_tracks.source_type = 'manual' THEN 1 ELSE 0 END) AS manual_track_count,
    SUM(CASE WHEN imported_playlist_tracks.local_file_url IS NOT NULL
        AND imported_playlist_tracks.local_file_url != '' THEN 1 ELSE 0 END) AS local_track_count
FROM users
LEFT JOIN imported_playlists
    ON imported_playlists.user_id = users.id
LEFT JOIN imported_playlist_tracks
    ON imported_playlist_tracks.imported_playlist_id = imported_playlists.id
GROUP BY users.id, users.name, users.email, users.role;

-- =========================================================
-- CHECKING QUERIES FOR MYSQL WORKBENCH
-- Run these after registering users or importing/uploading songs.
-- =========================================================

-- 1. See all tables.
SHOW TABLES;

-- 2. See safe user data without exposing password or password hash.
SELECT * FROM safe_user_profiles;

-- 3. See live user records in Workbench. Rerun this query after registering or editing users.
SELECT * FROM live_user_records ORDER BY updated_at DESC, id DESC;

-- 4. See login event history. Rerun this query to refresh the latest login attempts.
SELECT * FROM login_event_details ORDER BY created_at DESC, id DESC;

-- 5. See login summary by email and status.
SELECT
    email,
    status,
    COUNT(*) AS event_count,
    MAX(created_at) AS latest_attempt
FROM login_events
GROUP BY email, status
ORDER BY latest_attempt DESC;

-- 6. See user library totals.
SELECT * FROM user_library_summary;

-- 7. Confirm passwords are hashed, without showing the full password hash.
SELECT
    id,
    email,
    role,
    created_at,
    updated_at,
    LEFT(password, 18) AS password_hash_prefix,
    CASE
        WHEN password LIKE 'pbkdf2:%'
            OR password LIKE 'scrypt:%'
            OR password LIKE 'argon2:%'
        THEN 'OK - hashed'
        ELSE 'Warning - reset password'
    END AS password_check
FROM users;

-- 8. See playlists.
SELECT
    id,
    user_id,
    name,
    owner_name,
    track_count,
    spotify_url,
    created_at
FROM imported_playlists
ORDER BY id DESC;

-- 9. See tracks.
SELECT
    imported_playlist_tracks.id,
    imported_playlists.name AS playlist_name,
    imported_playlist_tracks.track_name,
    imported_playlist_tracks.artist_names,
    imported_playlist_tracks.source_type,
    imported_playlist_tracks.local_file_url,
    imported_playlist_tracks.spotify_url
FROM imported_playlist_tracks
INNER JOIN imported_playlists
    ON imported_playlists.id = imported_playlist_tracks.imported_playlist_id
ORDER BY imported_playlist_tracks.id DESC;
